### ISSUE TITLE
Got warning "You are manually calling a React.PropTypes validation function for the `scrollArea` prop on `t`. This is deprecated and will not work in production with the next major version"

### ISSUE THREAD

**Issue by Paramount1987** [souhe/reactScrollbar#74] opened 2017-02-03 08:42 UTC
Good afternoon. When I use component "ScrollArea", I get this warning "Warning: You are manually calling a React.PropTypes validation function for the `scrollArea` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details".
Could you tell how can I fix this?

**Comment by souhe** [comment] 2017-02-17 12:23
Hi @Paramount1987, when du you get this error exactly? And which version of `react-scrollbar` and `react` do you use?
I cannot reproduce it and I'm not manually calling React.PropTypes validation function so I'm confused ;)

**Comment by ra8ga** [comment] 2017-02-17 16:18
After updating react to newest react and react-dom and also react": "^15.4.2",  "react-dom": "^15.4.2" (I have current version of react-scrollbar - 0.5.1) I get different Warning.

"Warning: Unknown props `error`, `customClassName`, `input` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop"
link to description of this warning: https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by fdc-viktor-luft** [comment] 2017-02-23 08:38
That is the error-output I get with "react v15.2.1" and "react-scrollbar v0.5.1". Please remove those error-messages. Thank you.

ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `className` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `className` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `style` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `style` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `speed` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `speed` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `contentClassName` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `contentClassName` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `contentStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `contentStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `vertical` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `vertical` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `verticalContainerStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `verticalContainerStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `verticalScrollbarStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `verticalScrollbarStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `horizontal` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `horizontal` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `horizontalContainerStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `horizontalContainerStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `horizontalScrollbarStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `horizontalScrollbarStyle` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `onScroll` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `onScroll` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `contentWindow` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `contentWindow` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `ownerDocument` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `ownerDocument` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `smoothScrolling` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `smoothScrolling` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `minScrollSize` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `minScrollSize` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `swapWheelAxes` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `swapWheelAxes` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `stopScrollPropagation` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `stopScrollPropagation` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `focusableTabIndex` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'
ERROR: 'Warning: You are manually calling a React.PropTypes validation function for the `focusableTabIndex` prop on `t`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.'

**Comment by souhe** [comment] 2018-02-14 22:18
Fixed in the version 0.5.2

**Closed by souhe** 2018-02-14 22:18 UTC
