### ISSUE TITLE
update scroll when content get changed

### ISSUE THREAD

**Issue by cmnstmntmn** [souhe/reactScrollbar#1] opened 2015-04-27 08:49 UTC
let's say we're fetching the content from 5 to 5 sectonds, and it might be diffrend each time; 
so the scrollbar should reflect that

**Comment by souhe** [comment] 2015-05-04 16:14
I just pushed fixed version of the component. Now it could refresh scrollbar but only when children's content change comes from the parent of `ScrollArea`(children are stateless). 
The problem is when child component have it's own state and inside itself render some longer content. In that case it's not possible for `ScrollArea` component to know about this change. 

I could add some object(i.e. `scrollArea`) to context of each child. This object may have method `refresh()` to refresh scrollbar and you could manually force a refresh by using this method. What do you think about that?

**Comment by cmnstmntmn** [comment] 2015-05-04 16:21
:+1: that would be a neat solution to that!

**Comment by souhe** [comment] 2015-05-19 19:56
It appears that parent-based context will be in `React v0.14` and now only owner-based context works in react components. So for now I can't easily add `refresh()` method to the context. I'll do that after `React v0.14` released. Until that I'll try to find some workaround for this problem. Maybe you have some ideas?

**Closed** 2015-10-09 16:52 UTC
